### ISSUE TITLE
[Bug]: Can't extend browserslist config

### ISSUE THREAD

**Issue by CPatchane** [web-infra-dev/rsbuild#2443]
### Version

```sh
System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 66.70 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Browsers:
    Brave Browser: 120.1.61.116
    Chrome Canary: 127.0.6503.0
    Safari: 16.6
  npmPackages:
    @rsbuild/core: ^0.6.15 => 0.6.15
    @rsbuild/plugin-react: ^0.6.15 => 0.6.15
```

### Details

Hi here 👋 

I want to report that when using rsbuild (see the repo with a fresh create-rsbuild project), we can't `extends` a browserslist config from the npm package through the `package.json` (same thing if I do through a `.browserslistrc` file):
```
"browserslist": [
  "extends @getaround-eu/browserslist-config"
]
```
```
error   Failed to build.
error   Cannot find module '@getaround-eu/browserslist-config'
    at Function.webpackEmptyContext [as resolve] (/Users/me/Dev/projects/rsbuild-browserslist/node_modules/.pnpm/@rsbuild+shared@0.6.15_@swc+helpers@0.5.3/node_modules/@rsbuild/shared/compiled/browserslist/index.js:1913:10)
    at Object.loadQueries (/Users/me/Dev/projects/rsbuild-browserslist/node_modules/.pnpm/@rsbuild+shared@0.6.15_@swc+helpers@0.5.3/node_modules/@rsbuild/shared/compiled/browserslist/index.js:1424:51)
    at Function.select (/Users/me/Dev/projects/rsbuild-browserslist/node_modules/.pnpm/@rsbuild+shared@0.6.15_@swc+helpers@0.5.3/node_modules/@rsbuild/shared/compiled/browserslist/index.js:1159:26)
    at /Users/me/Dev/projects/rsbuild-browserslist/node_modules/.pnpm/@rsbuild+shared@0.6.15_@swc+helpers@0.5.3/node_modules/@rsbuild/shared/compiled/browserslist/index.js:353:29
    at Array.reduce (<anonymous>)
    at resolve (/Users/me/Dev/projects/rsbuild-browserslist/node_modules/.pnpm/@rsbuild+shared@0.6.15_@swc+helpers@0.5.3/node_modules/@rsbuild/shared/compiled/browserslist/index.js:343:34)
    at browserslist (/Users/me/Dev/projects/rsbuild-browserslist/node_modules/.pnpm/@rsbuild+shared@0.6.15_@swc+helpers@0.5.3/node_modules/@rsbuild/shared/compiled/browserslist/index.js:445:21)
    at browserslistToESVersion (/Users/me/Dev/projects/rsbuild-browserslist/node_modules/.pnpm/@rsbuild+shared@0.6.15_@swc+helpers@0.5.3/node_modules/@rsbuild/shared/dist/getBrowserslist.js:92:59)
    at handler (/Users/me/Dev/projects/rsbuild-browserslist/node_modules/.pnpm/@rsbuild+core@0.6.15/node_modules/@rsbuild/core/dist/plugins/target.js:41:69)
    at async Object.call (/Users/me/Dev/projects/rsbuild-browserslist/node_modules/.pnpm/@rsbuild+core@0.6.15/node_modules/@rsbuild/core/dist/initHooks.js:45:22)
 ELIFECYCLE  Command failed with exit code 1.
```

Note: When I passe that config directory through the `output.overrideBrowserslist` property in the `rsbuild.config.ts` config file, it works correctly.

### Reproduce link

https://github.com/CPatchane/rsbuild-browserslist-issue

### Reproduce Steps

Just run `pnpm dev` or `pnpm build`

**Comment by chenjiahan** [comment]
SWC uses `browserslist-rs` and its unreleased version supports the extends syntax:

https://github.com/browserslist/browserslist-rs/commit/04fcad2dcd30979c686f22eff289dbc8d6d6b47e

So we need to wait for browserslist-rs and SWC to release a new version, it will take some time.

**Comment by CPatchane** [comment]
> SWC uses browserslist-rs and its unreleased version supports the extends syntax:
https://github.com/browserslist/browserslist-rs/commit/04fcad2dcd30979c686f22eff289dbc8d6d6b47e
So we need to wait for browserslist-rs and SWC to release a new version, it will take some time.

Oh thanks a lot for your quick actions and response, until then I guess passing through the `output.overrideBrowserslist` is a good workaround 👍

**Comment by CPatchane** [comment]
> So we need to wait for browserslist-rs and SWC to release a new version, it will take some time.

@chenjiahan They just released the `v0.16.0` version that support that feature :)
https://github.com/browserslist/browserslist-rs/releases/tag/v0.16.0

**Comment by chenjiahan** [comment]
Nice 👍 The next step is to make SWC bump the dependency version, can you create an issue in the SWC repo?

**Comment by CPatchane** [comment]
Actually, it's already there https://github.com/swc-project/swc/pull/9023

**Comment by chenjiahan** [comment]
There is some discussion about switching from browserslist-rs to oxc-browserslist, which may take some time to resolve.

**Comment by CPatchane** [comment]
They chose to upgrade `browserslist-rc`, so we should be good :)
