### ISSUE TITLE
[Bug]: when using @rsbuild/plugin-vue as a plugin in vue project, an error is reported

### ISSUE THREAD

**Issue by hengistchan** [web-infra-dev/rsbuild#3114]
### Version

```sh
System:
    OS: macOS 14.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 1.24 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 17.1
  npmPackages:
    @rsbuild/plugin-less: 1.0.1-beta.9 => 1.0.1-beta.9 
    @rsbuild/plugin-vue: ^1.0.1-beta.9 => 1.0.1-beta.9
```

### Details

repack.config.ts
```js
export default defineConfig({
  mode: 'development',
  devtool: 'source-map',
  entry: {
    app: resolve(dirName, 'main.ts'),
  },
  plugins: [pluginVue()],
});
```

error log
```
> rspack serve

TypeError: plugin.apply is not a function
    at createCompiler (/Users/admin/.pnpm/@rspack+core@0.7.5_@swc+helpers@0.5.3/node_modules/@rspack/core/dist/rspack.js:54:24)
    at create (/Users/admin/.pnpm/@rspack+core@0.7.5_@swc+helpers@0.5.3/node_modules/@rspack/core/dist/rspack.js:89:26)
    at rspack (/Users/admin/.pnpm/@rspack+core@0.7.5_@swc+helpers@0.5.3/node_modules/@rspack/core/dist/rspack.js:115:37)
    at RspackCLI.createCompiler (/Users/admin/.pnpm/@rspack+cli@0.7.5_@rspack+core@0.7.5_@swc+helpers@0.5.3__@types+express@4.17.21_webpack@5.93.0/node_modules/@rspack/cli/dist/rspack-cli.js:66:34)
    at async Object.handler (/Users/admin/.pnpm/@rspack+cli@0.7.5_@rspack+core@0.7.5_@swc+helpers@0.5.3__@types+express@4.17.21_webpack@5.93.0/node_modules/@rspack/cli/dist/commands/serve.js:25:30)
```

### Reproduce link

no need link

### Reproduce Steps

1. `pnpm install`
2. `pnpm dev` -> `rspack serve`

**Comment by chenjiahan** [comment]
Rsbuild plugins can only be used with Rsbuild, you can not register it in an Rspack config file.

See: https://rsbuild.dev/guide/basic/configure-rsbuild
