### ISSUE TITLE
[Bug]: rsdoctor/rspack-plugin compile error when use antd-mobile date-picker component

### ISSUE THREAD

**Issue by VincentChris** [web-infra-dev/rsbuild#3310]
### Version

```sh
System: Mac os m2
Node: 18.16.0
pnpm: 8.15.8
antd-mobile: 5.27.1
```

### Details

  Rsbuild v1.0.1-beta.11

info    @rsdoctor/rspack-plugin enabled.
● web ━━━━━━━━━━━━━━━━━━━━━━━━━ (100%) emitting after emit                                                                                            module /Users/.../node_modules/.pnpm/antd-mobile@5.37.1_react-dom@18.3.1_react@18.3.1/node_modules/antd-mobile/es/components/date-picker/date-picker.css transform has error: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at Function.from (node:buffer:339:9)
    at appendModuleData (/Users/.../node_modules/.pnpm/@rsdoctor+core@0.3.11_@rspack+core@1.0.0/node_modules/@rsdoctor/core/dist/build-utils/build/module-graph/webpack/transform.js:129:166)
    at async Promise.all (index 374)
    at async appendModuleGraphByCompilation (/Users/.../node_modules/.pnpm/@rsdoctor+core@0.3.11_@rspack+core@1.0.0/node_modules/@rsdoctor/core/dist/build-utils/build/module-graph/webpack/transform.js:174:5)
    at async Object.<anonymous> (/Users/.../node_modules/.pnpm/@rsdoctor+core@0.3.11_@rspack+core@1.0.0/node_modules/@rsdoctor/core/dist/inner-plugins/plugins/ensureModulesChunkGraph.js:60:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}

### Reproduce link

no

### Reproduce Steps

1、rsbuild create project
2、add rs doctor plugin
3、add antd-mobile
4、use antd-mobile
5、pnpm  run  RSDOCTOR=true rsbuild build  script

**Comment by chenjiahan** [comment]
@easy1090 cc
