### ISSUE TITLE
Scss not working with plugin

### ISSUE THREAD

**Issue by R0N1n-dev** [web-infra-dev/rsbuild#3621]
### Version

```sh
System:
    OS: Linux 6.9 Pop!_OS 22.04 LTS
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 1.79 GB / 7.42 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Browsers:
    Brave Browser: 129.1.70.117
  npmPackages:
    @rsbuild/core: ^1.0.9 => 1.0.9 
    @rsbuild/plugin-sass: ^1.0.1 => 1.0.1 
    @rsbuild/plugin-vue: ^1.0.1 => 1.0.1
```

### Details

Came back to a project i had started using rsbuild and vue 3. It had started when rsbuild was at v0.4 so i updated it to the current version as seen in the results above and adding the Sass plugin as i had been using scss in the project. But on attempting to start the dev server, I get an error

```bash
mozeik@pop-os:~/rsvue$ bun run dev
$ rsbuild dev --open

  Rsbuild v1.0.9

  ➜ Local:    http://localhost:3000/
  ➜ Network:  http://192.168.0.95:3000/

error   Failed to start dev server.
error   TypeError: plugin.apply is not a function
    at createCompiler (/home/mozeik/rsvue/node_modules/@rspack/core/dist/rspack.js:54:24)
    at create (/home/mozeik/rsvue/node_modules/@rspack/core/dist/rspack.js:89:26)
    at rspack (/home/mozeik/rsvue/node_modules/@rspack/core/dist/rspack.js:115:37)
    at createCompiler (file:///home/mozeik/rsvue/node_modules/@rsbuild/core/dist/index.js:6827:49)
    at async createCompiler2 (file:///home/mozeik/rsvue/node_modules/@rsbuild/core/dist/index.js:9089:24)
    at async startCompile (file:///home/mozeik/rsvue/node_modules/@rsbuild/core/dist/index.js:8801:40)
    at async createDevServer (file:///home/mozeik/rsvue/node_modules/@rsbuild/core/dist/index.js:8844:45)
    at async Object.startDevServer (file:///home/mozeik/rsvue/node_modules/@rsbuild/core/dist/index.js:9112:26)
    at async _Command.<anonymous> (file:///home/mozeik/rsvue/node_modules/@rsbuild/core/dist/index.js:13401:7)
error: script "dev" exited with code 1
```

### Reproduce link

https://stackblitz.com/github/R0N1n-dev/RsVue

### Reproduce Steps

1. Execute 'npm run dev'.

**Comment by chenjiahan** [comment]
The `@rsbuild/plugin-sass` should be registered in `plugins` instead of `tools.rspack.plugins`:

![Image](https://github.com/user-attachments/assets/973d4a92-3b7c-47cb-b514-644104f8083f)
