### ISSUE TITLE
[Bug]: serve always unexpected stop

### ISSUE THREAD

**Issue by summer-8848** [web-infra-dev/rsbuild#4120]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700
    Memory: 15.84 GB / 31.68 GB
Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.19041.4355
npmPackages:
    @rsbuild/core: ^1.1.7 => 1.1.7
    @rsbuild/plugin-assets-retry: ^1.0.6 => 1.0.6
    @rsbuild/plugin-babel: ^1.0.3 => 1.0.3
    @rsbuild/plugin-check-syntax: ^1.1.0 => 1.1.0
    @rsbuild/plugin-css-minimizer: ^1.0.2 => 1.0.2
    @rsbuild/plugin-image-compress: ^1.0.2 => 1.0.2
    @rsbuild/plugin-rem: ^1.0.2 => 1.0.2
    @rsbuild/plugin-sass: ^1.1.1 => 1.1.1
    @rsbuild/plugin-type-check: ^1.1.0 => 1.1.0
    @rsbuild/plugin-vue: ^1.0.5 => 1.0.5
    @rsbuild/plugin-vue-jsx: ^1.0.1 => 1.0.1
```

### Details

/www/vant-test/node_modules/.pnpm/@rspack+core@1.1.4_@swc+helpers@0.5.15/node_modules/@rspack/core/dist/index.js:2807
      (d) => __privateGet(this, _inner).addFileDependencies(d)
                                        ^

Error: Unable to access compilation with id = CompilationId(35) now. The compilation have been removed on the Rust side. The latest compilation id is CompilationId(39)
    at MergeCaller.callFn (/www/vant-test/node_modules/.pnpm/@rspack+core@1.1.4_@swc+helpers@0.5.15/node_modules/@rspack/core/dist/index.js:2807:41)
    at MergeCaller.finalCall [as _onTimeout] (/www/vant-test/node_modules/.pnpm/@rspack+core@1.1.4_@swc+helpers@0.5.15/node_modules/@rspack/core/dist/index.js:2672:12)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  code: 'GenericFailure'
}

Node.js v22.11.0

进程已结束，退出代码为 1

### Reproduce link

http://no-demo.dev

### Reproduce Steps

pnpm i
pnpm run dev

I'm testing this code:
```
import { useRoute } from 'vue-router';

export function parseParams() {
  const route = useRoute();
  const encoded = route.query.p;
  let params = null;

  if (!encoded) {
    return;
  }
  const decoded = atob(encoded);
  params = JSON.parse(decoded);
  console.log('Original object2:', params);
  return params;
}
```
sample:
`http://192.168.1.9:8000/#/?p=eyJ1c2VySWQiOiIxMjMiLCJuYW1lIjoiSm9obiJ9`

**Comment by summer-8848** [comment]
Reproduce link: https://github.com/summer-8848/rsbuild_demo

Thanks

**Comment by summer-8848** [comment]
@chenjiahan 
给我的感觉像是eslint或prettier格式化导致rsbuild刷新太多次导致的，webstorm配置了prettier自动格式化

It feels to me like eslint or prettier formatting causes rsbuild to refresh too many times, webstorm configures prettier for automatic formatting

**Comment by chenjiahan** [comment]
Should be fixed in Rspack v1.1.5 an Rsbuild v1.1.8, can you upgrade the version and try again?

Related PR: https://github.com/web-infra-dev/rspack/pull/8591

**Comment by summer-8848** [comment]
Nice!!! 
Sorry for not updating in time.
