### ISSUE TITLE
[Bug]: Build failure: Failed to resolve .png

### ISSUE THREAD

**Issue by jiahao-atl** [web-infra-dev/rsbuild#964]
### Version

```sh
System:
    OS: macOS 14.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 9.28 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 17.2
  npmPackages:
    @rsbuild/core: ^0.2.4 => 0.2.4
    @rsbuild/plugin-react: ^0.2.4 => 0.2.4
    @rsbuild/plugin-svgr: ^0.2.4 => 0.2.4
```

### Details

```
error   Compile error:
Failed to compile, check the errors for troubleshooting.
× Failed to resolve ./images/message-icon-warning-1.png in css|/Users/jchen8/support-form-app/node_modules/@rsbuild/shared/compiled/postcss-loader/index.js??ruleSet[1].rules[7].oneOf[1].use[0]!/
  │ Users/jchen8/support-form-app/node_modules/@rsbuild/shared/compiled/resolve-url-loader/index.js??ruleSet[1].rules[7].oneOf[1].use[1]!/Users/jchen8/support-form-app/node_modules/@rsbuild/shared/
  │ compiled/sass-loader/index.js??ruleSet[1].rules[7].oneOf[1].use[2]!/Users/jchen8/support-form-app/src/assets/styles/main.scss

error   Failed to build.
error   Rspack build failed!
    at /Users/jchen8/support-form-app/node_modules/@rsbuild/core/dist/provider/core/build.js:32:35
    at finalCallback (/Users/jchen8/support-form-app/node_modules/@rspack/core/dist/Compiler.js:335:21)
    at /Users/jchen8/support-form-app/node_modules/@rspack/core/dist/Compiler.js:359:40
    at Hook.eval [as callAsync] (eval at create (/Users/jchen8/support-form-app/node_modules/@rspack/core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/jchen8/support-form-app/node_modules/@rspack/core/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/jchen8/support-form-app/node_modules/@rspack/core/dist/Compiler.js:354:41
    at /Users/jchen8/support-form-app/node_modules/@rspack/core/dist/Compiler.js:391:21
error Command failed with exit code 1.
```

The file `./images/message-icon-warning-1.png ` exists and builds without error using webpack. 

config:
```typescript
import { defineConfig } from '@rsbuild/core';
import { pluginReact } from '@rsbuild/plugin-react';
import { pluginSvgr } from '@rsbuild/plugin-svgr';


export default defineConfig({
  plugins: [pluginReact(),pluginSvgr()],
});
```

place where the png is imported (an scss file):
```scss
	&.error,
	&.warning-1{
		background-image:url(../images/message-icon-warning-1.png);
	}
```

### Reproduce link

N/A

### Reproduce Steps

Sorry, I am unable to provide reproduce code/link because this is a company-internal project.
I'd appreciate any help and guidance on resolving this error. Hopefully it's just a missing config on my side. Maybe I need an extra plugin to handle png/scss?

**Comment by chenjiahan** [comment]
For internal project, you can try to create a minimal reproduction repo in GitHub, this would be very helpful for us ❤️

**Comment by chenjiahan** [comment]
thanks for your support!
